// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using covid19.App.Persistencia;

namespace covid19.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20210920211251_Inicial4")]
    partial class Inicial4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("covid19.App.Dominio.Diagnostico", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("estado_covid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fecha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unidad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("diagnosticos");
                });

            modelBuilder.Entity("covid19.App.Dominio.Foco", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("num_contagios")
                        .HasColumnType("int");

                    b.Property<string>("unidad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("focos");
                });

            modelBuilder.Entity("covid19.App.Dominio.Personas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("edad")
                        .HasColumnType("int");

                    b.Property<string>("estado_covid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Personas");
                });

            modelBuilder.Entity("covid19.App.Dominio.Salones", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("aforo")
                        .HasColumnType("int");

                    b.Property<DateTime>("hora")
                        .HasColumnType("datetime2");

                    b.Property<int>("numero_puesto")
                        .HasColumnType("int");

                    b.Property<string>("sede")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unidad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("salones");
                });

            modelBuilder.Entity("covid19.App.Dominio.Sede", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("cant_salones")
                        .HasColumnType("int");

                    b.Property<string>("nombre_sede")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("sedes");
                });

            modelBuilder.Entity("covid19.App.Dominio.Directivo", b =>
                {
                    b.HasBaseType("covid19.App.Dominio.Personas");

                    b.Property<string>("unidad")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Directivo");
                });

            modelBuilder.Entity("covid19.App.Dominio.Estudiante", b =>
                {
                    b.HasBaseType("covid19.App.Dominio.Personas");

                    b.Property<string>("carrera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("semestre")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Estudiante");
                });

            modelBuilder.Entity("covid19.App.Dominio.HistoriaClinica", b =>
                {
                    b.HasBaseType("covid19.App.Dominio.Personas");

                    b.Property<string>("fecha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("seguimiento")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("HistoriaClinica");
                });

            modelBuilder.Entity("covid19.App.Dominio.PersonalAseo", b =>
                {
                    b.HasBaseType("covid19.App.Dominio.Personas");

                    b.Property<string>("turno")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("PersonalAseo");
                });

            modelBuilder.Entity("covid19.App.Dominio.Profesor", b =>
                {
                    b.HasBaseType("covid19.App.Dominio.Personas");

                    b.Property<string>("asignatura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("departamento")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Profesor");
                });
#pragma warning restore 612, 618
        }
    }
}
